// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(1215373692).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CleanupDownloads(): $CancellablePromise<void> {
    return $Call.ByID(1337919975);
}

export function DownloadUpdate(downloadURL: string, progressCallback: any): $CancellablePromise<string> {
    return $Call.ByID(1447067367, downloadURL, progressCallback);
}

export function GetCurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(1838294253);
}

export function InstallUpdate(apkPath: string): $CancellablePromise<void> {
    return $Call.ByID(1230765532, apkPath);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
