// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TokenData {
    /**
     * Creates a new TokenData instance.
     * @param {Partial<TokenData>} [$$source = {}] - The source object to create the TokenData.
     */
    constructor($$source = {}) {
        if (!("access_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["access_token"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["refresh_token"] = undefined;
        }
        if (!("token_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token_type"] = "";
        }
        if (!("expires_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expires_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TokenData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TokenData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TokenData(/** @type {Partial<TokenData>} */($$parsedSource));
    }
}
