// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TokenData {
    "access_token": string;
    "refresh_token"?: string;
    "token_type": string;
    "expires_at": number;

    /** Creates a new TokenData instance. */
    constructor($$source: Partial<TokenData> = {}) {
        if (!("access_token" in $$source)) {
            this["access_token"] = "";
        }
        if (!("token_type" in $$source)) {
            this["token_type"] = "";
        }
        if (!("expires_at" in $$source)) {
            this["expires_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TokenData instance from a string or object.
     */
    static createFrom($$source: any = {}): TokenData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TokenData($$parsedSource as Partial<TokenData>);
    }
}
