// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAuthorizationURL(): $CancellablePromise<string> {
    return $Call.ByID(3228093349);
}

/**
 * GetPendingCode returns and clears any pending authorization code.
 */
export function GetPendingCode(): $CancellablePromise<string> {
    return $Call.ByID(1634895015);
}

export function GetToken(): $CancellablePromise<$models.TokenData | null> {
    return $Call.ByID(3947099560).then(($result: any) => {
        return $$createType1($result);
    });
}

export function HandleCallback(code: string): $CancellablePromise<$models.TokenData | null> {
    return $Call.ByID(409443104, code).then(($result: any) => {
        return $$createType1($result);
    });
}

export function IsAuthenticated(): $CancellablePromise<boolean> {
    return $Call.ByID(1479351524);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(3726188687);
}

/**
 * SaveToken saves an access token directly (for implicit grant flow)
 */
export function SaveToken(accessToken: string): $CancellablePromise<void> {
    return $Call.ByID(1975979673, accessToken);
}

/**
 * SetPendingCode stores an authorization code for later retrieval by the frontend.
 */
export function SetPendingCode(code: string): $CancellablePromise<void> {
    return $Call.ByID(3950991427, code);
}

/**
 * StartCallbackServer starts a temporary HTTP server to receive the OAuth callback.
 * It tries the configured port first, then falls back to nearby ports.
 */
export function StartCallbackServer(): $CancellablePromise<void> {
    return $Call.ByID(3871667447);
}

/**
 * StopCallbackServer shuts down the callback server.
 */
export function StopCallbackServer(): $CancellablePromise<void> {
    return $Call.ByID(2528056125);
}

// Private type creation functions
const $$createType0 = $models.TokenData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
