// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAuthorizationURL(): $CancellablePromise<string> {
    return $Call.ByID(3228093349);
}

export function GetToken(): $CancellablePromise<$models.TokenData | null> {
    return $Call.ByID(3947099560).then(($result: any) => {
        return $$createType1($result);
    });
}

export function HandleCallback(code: string): $CancellablePromise<$models.TokenData | null> {
    return $Call.ByID(409443104, code).then(($result: any) => {
        return $$createType1($result);
    });
}

export function IsAuthenticated(): $CancellablePromise<boolean> {
    return $Call.ByID(1479351524);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(3726188687);
}

/**
 * SaveToken saves an access token directly (for implicit grant flow)
 */
export function SaveToken(accessToken: string): $CancellablePromise<void> {
    return $Call.ByID(1975979673, accessToken);
}

// Private type creation functions
const $$createType0 = $models.TokenData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
