// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAuthorizationURL() {
    return $Call.ByID(3228093349);
}

/**
 * @returns {$CancellablePromise<$models.TokenData | null>}
 */
export function GetToken() {
    return $Call.ByID(3947099560).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} code
 * @returns {$CancellablePromise<$models.TokenData | null>}
 */
export function HandleCallback(code) {
    return $Call.ByID(409443104, code).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsAuthenticated() {
    return $Call.ByID(1479351524);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(3726188687);
}

// Private type creation functions
const $$createType0 = $models.TokenData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
