// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConsumePendingCode clears the pending authorization code after successful use.
 * @returns {$CancellablePromise<void>}
 */
export function ConsumePendingCode() {
    return $Call.ByID(911589497);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAuthorizationURL() {
    return $Call.ByID(3228093349);
}

/**
 * GetPendingCode returns the pending authorization code without clearing it.
 * Use ConsumePendingCode after successful token exchange to clear it.
 * @returns {$CancellablePromise<string>}
 */
export function GetPendingCode() {
    return $Call.ByID(1634895015);
}

/**
 * @returns {$CancellablePromise<$models.TokenData | null>}
 */
export function GetToken() {
    return $Call.ByID(3947099560).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} code
 * @returns {$CancellablePromise<$models.TokenData | null>}
 */
export function HandleCallback(code) {
    return $Call.ByID(409443104, code).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsAuthenticated() {
    return $Call.ByID(1479351524);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(3726188687);
}

/**
 * SaveToken saves an access token directly (for implicit grant flow)
 * @param {string} accessToken
 * @returns {$CancellablePromise<void>}
 */
export function SaveToken(accessToken) {
    return $Call.ByID(1975979673, accessToken);
}

/**
 * SetPendingCode stores an authorization code for later retrieval by the frontend.
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function SetPendingCode(code) {
    return $Call.ByID(3950991427, code);
}

/**
 * StartCallbackServer starts a temporary HTTP server to receive the OAuth callback.
 * It tries the configured port first, then falls back to nearby ports.
 * @returns {$CancellablePromise<void>}
 */
export function StartCallbackServer() {
    return $Call.ByID(3871667447);
}

/**
 * StopCallbackServer shuts down the callback server.
 * @returns {$CancellablePromise<void>}
 */
export function StopCallbackServer() {
    return $Call.ByID(2528056125);
}

// Private type creation functions
const $$createType0 = $models.TokenData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
