// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PlatformInfo {
    /**
     * Creates a new PlatformInfo instance.
     * @param {Partial<PlatformInfo>} [$$source = {}] - The source object to create the PlatformInfo.
     */
    constructor($$source = {}) {
        if (!("os" in $$source)) {
            /**
             * "windows", "darwin", "linux", "android", "ios"
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * "amd64", "arm64", etc.
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("isDesktop" in $$source)) {
            /**
             * windows, macos, linux
             * @member
             * @type {boolean}
             */
            this["isDesktop"] = false;
        }
        if (!("isMobile" in $$source)) {
            /**
             * android, ios
             * @member
             * @type {boolean}
             */
            this["isMobile"] = false;
        }
        if (!("isTouch" in $$source)) {
            /**
             * mobile or tablet
             * @member
             * @type {boolean}
             */
            this["isTouch"] = false;
        }
        if (!("hasHover" in $$source)) {
            /**
             * true on desktop (mouse)
             * @member
             * @type {boolean}
             */
            this["hasHover"] = false;
        }
        if (!("hasKeyboard" in $$source)) {
            /**
             * true on desktop
             * @member
             * @type {boolean}
             */
            this["hasKeyboard"] = false;
        }
        if (!("screenSmall" in $$source)) {
            /**
             * < 768px
             * @member
             * @type {boolean}
             */
            this["screenSmall"] = false;
        }
        if (!("screenMedium" in $$source)) {
            /**
             * 768-1024px
             * @member
             * @type {boolean}
             */
            this["screenMedium"] = false;
        }
        if (!("screenLarge" in $$source)) {
            /**
             * > 1024px
             * @member
             * @type {boolean}
             */
            this["screenLarge"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlatformInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlatformInfo(/** @type {Partial<PlatformInfo>} */($$parsedSource));
    }
}
