// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PlatformInfo {
    /**
     * "windows", "darwin", "linux", "android", "ios"
     */
    "os": string;

    /**
     * "amd64", "arm64", etc.
     */
    "arch": string;

    /**
     * windows, macos, linux
     */
    "isDesktop": boolean;

    /**
     * android, ios
     */
    "isMobile": boolean;

    /**
     * mobile or tablet
     */
    "isTouch": boolean;

    /**
     * true on desktop (mouse)
     */
    "hasHover": boolean;

    /**
     * true on desktop
     */
    "hasKeyboard": boolean;

    /**
     * < 768px
     */
    "screenSmall": boolean;

    /**
     * 768-1024px
     */
    "screenMedium": boolean;

    /**
     * > 1024px
     */
    "screenLarge": boolean;

    /** Creates a new PlatformInfo instance. */
    constructor($$source: Partial<PlatformInfo> = {}) {
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("isDesktop" in $$source)) {
            this["isDesktop"] = false;
        }
        if (!("isMobile" in $$source)) {
            this["isMobile"] = false;
        }
        if (!("isTouch" in $$source)) {
            this["isTouch"] = false;
        }
        if (!("hasHover" in $$source)) {
            this["hasHover"] = false;
        }
        if (!("hasKeyboard" in $$source)) {
            this["hasKeyboard"] = false;
        }
        if (!("screenSmall" in $$source)) {
            this["screenSmall"] = false;
        }
        if (!("screenMedium" in $$source)) {
            this["screenMedium"] = false;
        }
        if (!("screenLarge" in $$source)) {
            this["screenLarge"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PlatformInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlatformInfo($$parsedSource as Partial<PlatformInfo>);
    }
}
