// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.PlatformInfo>}
 */
export function Detect() {
    return $Call.ByID(2432106113).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetOS() {
    return $Call.ByID(3630969452);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDesktop() {
    return $Call.ByID(4244518666);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsMobile() {
    return $Call.ByID(1738614204);
}

// Private type creation functions
const $$createType0 = $models.PlatformInfo.createFrom;
