// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Detect(): $CancellablePromise<$models.PlatformInfo> {
    return $Call.ByID(2432106113).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetOS(): $CancellablePromise<string> {
    return $Call.ByID(3630969452);
}

export function IsDesktop(): $CancellablePromise<boolean> {
    return $Call.ByID(4244518666);
}

export function IsMobile(): $CancellablePromise<boolean> {
    return $Call.ByID(1738614204);
}

// Private type creation functions
const $$createType0 = $models.PlatformInfo.createFrom;
